adding functions in seperate file.

diff --git a/delPWDfrompath b/delPWDfrompath
--- a/delPWDfrompath
+++ b/delPWDfrompath
@@ -13,36 +13,27 @@
 #You should have received a copy of the GNU General Public License
 #along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-_srcsbinpath=$PWD
+_curdir=$PWD
+_srcsbinpath=$(dirname $(readlink -f $0))
 
-function escapepath(){
-	local _thep
-	_thep=$1
-	_thep=${_thep//\//\\/}
-	echo "$_thep"
-}
-
-function replaceline(){
-	local _pattern _replace _file
-	_pattern=$1
-	_replace=$2
-	_file=$3
-	sed -i "/$_pattern/ { c \
-	$_replace
-	}" "$_file"
-}
+if [ -s "$_srcsbinpath/functions" ] ; then
+	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
+fi
 
 _bashrcfile="$(eval echo $1)"
 if [ -z "$_bashrcfile" ] ; then
 	_bashrcfile="$(eval echo ~/.bashrc)"
 fi
 
-if echo $PATH | grep -qo ":$_srcsbinpath" ; then
-export PATH=${PATH//:$(escapepath "$_srcsbinpath")}
+if echo $PATH | grep -qo ":$_curdir" ; then
+export PATH=${PATH//:$(escapepath "$_curdir")}
 fi
 
-if _grepline=$(grep -F "export PATH=\$PATH:$_srcsbinpath" "$_bashrcfile") ; then
+if _grepline=$(grep -F "export PATH=\$PATH:$_curdir" "$_bashrcfile") ; then
 	if [ "${_grepline:0:1}" != "#" ] ; then
-		replaceline "$(escapepath "export PATH=\$PATH:$_srcsbinpath")" "#export PATH=\$PATH:$_srcsbinpath" "$_bashrcfile"
+		replaceline "$(escapepath "export PATH=\$PATH:$_curdir")" "#export PATH=\$PATH:$_curdir" "$_bashrcfile"
 	fi
 fi
diff --git a/fixbacklight b/fixbacklight
--- a/fixbacklight
+++ b/fixbacklight
@@ -14,39 +14,12 @@
 #along with this program.  If not, see <http://www.gnu.org/licenses/>.
 _srcsbinpath=$(dirname $(readlink -f $0))
 
-function confirmtogo(){
-	local _conit _valtogo _msg
-	_msg=$1
-	_valtogo=$2
-	if [ -z "$_msg" ] ; then
-		exit 1
-	fi
-	read -p "$_msg" _conit
-	_conit=${_conit,,}
-	if [ -z "$_valtogo" ] ; then
-		_valtogo="yes"
-	else
-		_valtogo=${_valtogo,,}
-	fi
-	if [ "$_valtogo" = "notempty" ] ; then
-		if [ ! -z "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ "$_valtogo" = "pathexist" ] ; then
-		if [ -e "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
-		return 0
-	fi
-	return 1
-}
+if [ -s "$_srcsbinpath/functions" ] ; then
+	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
+fi
 
 if [ ! -f $_srcsbinpath/timeout3 ] ; then
 	echo "Required $_srcsbinpath/timeout3 file not found!" 1>&2
diff --git a/getgitrepo b/getgitrepo
--- a/getgitrepo
+++ b/getgitrepo
@@ -43,44 +43,12 @@ else
 	exit 1
 fi
 
-function confirmtogo(){
-	local _conit _valtogo _msg
-	_msg=$1
-	_valtogo=$2
-	if [ -z "$_msg" ] ; then
-		exit 1
-	fi
-	read -p "$_msg" _conit
-	_conit=${_conit,,}
-	if [ -z "$_valtogo" ] ; then
-		_valtogo="yes"
-	else
-		_valtogo=${_valtogo,,}
-	fi
-	if [ "$_valtogo" = "notempty" ] ; then
-		if [ ! -z "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ "$_valtogo" = "pathexist" ] ; then
-		if [ -e "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
-		return 0
-	fi
-	return 1
-}
-
-function strtoarry(){
-	local _str _retarray _deli _c _l;_str=$1 _retarray=$2 _deli=$3
-	_c=-1;while read -r _l; do _c=$((_c+1));eval $_retarray[$_c]='$_l';done <<< "$(echo $_str | sed -e "s/$_deli/\n/g")"
-}
+if [ -s "$_srcsbinpath/functions" ] ; then
+	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
+fi
 
 _scheme=${_baseurl%%://*}
 _scheme=${_scheme,,}
diff --git a/nginxcompile b/nginxcompile
--- a/nginxcompile
+++ b/nginxcompile
@@ -34,39 +34,12 @@ if [ -z "$1" ] && [ "${1%%-*}" = "nginx" ]; then
 	shift
 fi
 
-function confirmtogo(){
-	local _conit _valtogo _msg
-	_msg=$1
-	_valtogo=$2
-	if [ -z "$_msg" ] ; then
-		exit 1
-	fi
-	read -p "$_msg" _conit
-	_conit=${_conit,,}
-	if [ -z "$_valtogo" ] ; then
-		_valtogo="yes"
-	else
-		_valtogo=${_valtogo,,}
-	fi
-	if [ "$_valtogo" = "notempty" ] ; then
-		if [ ! -z "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ "$_valtogo" = "pathexist" ] ; then
-		if [ -e "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
-		return 0
-	fi
-	return 1
-}
+if [ -s "$_srcsbinpath/functions" ] ; then
+	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
+fi
 
 if [ ! -z "$1" ] ; then
 	if [ -d "$1" ] ; then
diff --git a/sflatest b/sflatest
--- a/sflatest
+++ b/sflatest
@@ -30,10 +30,12 @@ if [ -z "$1" ] ; then
 fi
 _baseurl="$1"
 
-function strtoarry(){
-	local _str _retarray _deli _c _l;_str=$1 _retarray=$2 _deli=$3
-	_c=-1;while read -r _l; do _c=$((_c+1));eval $_retarray[$_c]='$_l';done <<< "$(echo $_str | sed -e "s/$_deli/\n/g")"
-}
+if [ -s "$_srcsbinpath/functions" ] ; then
+	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
+fi
 
 _scheme=${_baseurl%%://*}
 _scheme=${_scheme,,}
diff --git a/sshsetup b/sshsetup
--- a/sshsetup
+++ b/sshsetup
@@ -26,13 +26,12 @@ if [ -z _knownhostfile ] ; then
 	fi
 fi
 
-function isinteractive(){
-	fd=0   # stdin
-	if [ -t "$fd" ] || [ -p /dev/stdin ] ; then
-	  return 0
-	fi
-	return 1
-}
+if [ -s "$_srcsbinpath/functions" ] ; then
+	. $_srcsbinpath/functions	
+else
+	echo "$_srcsbinpath/functions file not found!" 1>&2
+	exit 1
+fi
 
 if ! isinteractive ; then
 	echo "This script can't run in non-interactive mode...exiting." 1>&2
